### PR TITLE
Attrs

### PR DESCRIPTION
**Pull request by cpage192**
Converted from dataclass to attrs, did some basic type checking with that

### CODE REVIEW

**Comment by MattToast** [comment]
Run `make style` and commit the changes. That should allow tests to pass!

**Comment by cpage192** [comment]
make test, make type, and make style all return no errors, yet still getting errors here

**Comment by MattToast** [comment]
Whoops, meant `make style-all`

**Review by MattToast — APPROVED** [review]
lgtm

**Pull request merged**
